data_path: data/sample.csv
result_dir: result/sample

column: #各データが入っている列番号　（番号は0スタートなことに注意）
  band_name: 2    #バンド名
  members: [3, 4, 5, 6, 7] #メンバー名 (期番号+本名など、人を区別する名前)
  possible_schedules: [9, 10, 11, 12, 13] #候補スケジュール (1か0が入る)
  info: [2, 1, 3, 4, 5, 6, 7, 14]  # 出力ファイルに含めたい情報を含む列番号

constraint: #付け加えたい制約条件
  close_schedule: # 同じメンバーがいるバンド同士は間を離す
    active: true # この制約条件を有効にするか
    gap: 1  # 何バンド間を空けるか (0にすると隣同士を許すことになるから、無効にするのと同じ)

target: 1 # 目的関数の種類の番号 1 同じメンバーがいるバンド間隔の和を最大化する 
